condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
hard_tabs = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true