[package]
name = "builders"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.1"

[dependencies]
anyhow = "1.0.98"
regex = { version = "1.11.1", default-features = false, features = ["unicode-gencat", "unicode-script"] }
twilight-model = "0.16.0"
twilight-validate = "0.16.0"
